<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no">
    <title>Videojuego</title>
    <link rel="stylesheet" href="css/styles.css">
</head>

<body>

    <div class="header">
        <div class="logo">
            <button id="button-logo">
                <img src="images/Logo2.png" alt="Logo">
            </button>
            <span class="inside">Inside</span>
            <span class="tagline">Legendary videogames ONLINE</span>
        </div>
        <div class="quote">
            <img src="images/try-hard.jpg" alt="Wizard">
            <span>"No dejamos de jugar porque nos hacemos viejos... Envejecemos porque dejamos de jugar".</span>
        </div>
    </div>

    <section id="game-section">
        <div class="game-container glass-effect">
            <div id="game">
                <iframe src="html5game/index.html" width="800" height="600"></iframe>
            </div>
            <div class="colorful-bar"></div>
        </div>
    </section>

    <section id="information-section">
        <div class="info-section">
            <h3>Sobre Nosotros</h3>
            <p>
                Somos estudiantes de la Universidad Politécnica de Sinaloa. Este videojuego ha sido desarrollado como
                parte de nuestro servicio social. Es un proyecto sin ánimo de lucro y estamos emocionados de compartir
                esta
                nueva experiencia con todos ustedes.
            </p>
        </div>
    </section>

    <section id="comment-section">
        <div class="comments-section">
            <h2>Comentarios</h2>
            <div id="disqus_thread"></div>
            <noscript>Por favor, habilita JavaScript para ver los <a href="https://disqus.com/?ref_noscript">comentarios
                    de
                    Disqus.</a></noscript>
        </div>
    </section>

    <div class="footer">
        <button id="button-Upsin">
            <img height="50px" width="40px" src="images/UPSIN_png.png" alt="Logo" />
            Todos los derechos reservados al equipo Inside. Servicio social por la Universidad Politécnica de Sinaloa.
        </button>
    </div>

    <script src="js/scripts.js"></script>
</body>

</html>

